services:
  database:
    image: postgres:15
    container_name: juscash_database
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: juscash2025
      POSTGRES_DB: juscash_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./juscash-api
    container_name: juscash_api
    ports:
      - "5000:5000"
      # - "5555:5555"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql://postgres:juscash2025@database:5432/juscash_db
    volumes:
    - ./juscash-api:/usr/src/app
    - /usr/src/app/node_modules

  front:
    build: ./juscash-front
    container_name: juscash_front
    ports:
      - "3000:3000"

volumes:
  postgres_data: